# -*- coding: utf-8 -*-
"""atividade 5 programação

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QScNV0djkH3O084J6rmDeqHTX_sP01CC
"""

def analisar_microclima():
    # 1. Estrutura de Lista de Listas: [Local, Temp, Umidade, IQA]

    dados_locais = [
        ["Parque do Carmo", 22.5, 72.5, 35],
        ["Estação Dom Bosco", 26.0, 60.0, 80],
        ["UNICID Tatuapé", 25.0, 63.0, 72]
    ]

    print(f"{'Local':<20} | {'Temp':<5} | {'IQA':<5} | {'Classificação':<15} | {'Nota Conforto'}")
    print("-" * 75)


    for local in dados_locais:
        nome = local[0]
        temp = local[1]
        umid = local[2]
        iqa = local[3]

        # 3. Match-Case para Classificação do Ar
        match iqa:
            case i if i <= 40:
                classificacao = "Boa"
                peso_iqa = 1.0
            case i if i <= 80:
                classificacao = "Moderada"
                peso_iqa = 0.7
            case i if i <= 120:
                classificacao = "Ruim"
                peso_iqa = 0.4
            case _:
                classificacao = "Péssima"
                peso_iqa = 0.1

        # 4. Fórmula Matemática Complexa: Nota de Conforto (0 a 10)
        # O conforto é maior se a temp for próxima de 23°C e umidade ~50%


       # Penalidade por calor extremo
        temp_ideal = 23
        penalidade_temp = abs(temp - temp_ideal) / 5

        # Penalidade por secura/umidade excessiva
        if 40 <= umid <= 60:
            penalidade_umid = 0
        else:
            penalidade_umid = 1

        # Cálculo da Nota
        nota_final = (peso_iqa * 10) - penalidade_temp - (penalidade_umid * 1.5)

        # Garante que a nota esteja entre 0 e 10
        nota_final = max(0, min(10, nota_final))

        print(f"{nome:<20} | {temp:<5.1f} | {classificacao:<13} | {nota_final:.2f}")

# Executa a análise
analisar_microclima()

import time

# Mapa Física: Nomes dos Locais e Estados
mapa_locais = ["Sala de Trabalho", "Antecedentes Escada", "Escada 1", "Patamar", "Escada 2", "Corredor Final", "RUA - SAÍDA"]
mapa_obstaculos = ["porta_trancada", "livre", "livre", "aglomeracao", "livre", "fumaca", "final"]

# Estado do Agente
inventario = {"tem_chave_mestra": False}
energia = 100
posicao = 0 # Começa no nó 0
sucesso = False

print("--- Iniciando Simulação de Evacuação ---")

while not sucesso and energia > 0:
    local_atual = mapa_locais[posicao]
    obstaculo_atual = mapa_obstaculos[posicao]

    print(f"\n[Agente] Chegou em: {local_atual}")
    energia -= 10
    time.sleep(0.5)

    # Lógica de Avaliação de Obstáculos (Ifs Aninhados)
    if obstaculo_atual == "porta_trancada":
        if inventario["tem_chave_mestra"]:
            print(">> Porta trancada, mas chave usada. Passando.")
            posicao += 1
        else:
            print(">> PORTA TRANCADA! Procurando chave...")
            # Simulando pegar a chave no ambiente
            inventario["tem_chave_mestra"] = True
            print(">> Chave encontrada no ambiente. Tentando novamente.")
            # Nao avança, tenta no próximo ciclo

    elif obstaculo_atual == "fumaca":
        print(">> Fumaça intensa! Abaixando-se para avançar.")
        posicao += 1

    elif obstaculo_atual == "final":
        print(">> O AR ESTÁ LIVRE! Evacuação concluída com sucesso!")
        sucesso = True

    elif obstaculo_atual == "aglomeracao":
        print(">> Muita gente na escada. Aguardando 2 segundos.")
        energia -= 5
        posicao += 1

    else:
        print(">> Caminho livre.")
        posicao += 1

    if energia <= 0:
        print("\n[ERRO] Agente ficou sem energia/tempo. Fuga falhou.")

if sucesso:
    print("\nSimulação Finalizada. Resultado: SUCESSO.")
else:
    print("\nSimulação Finalizada. Resultado: FALHA.")