# -*- coding: utf-8 -*-
"""emoji_com_dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c303EHGv32Pp9OgD-03UC2enIWi1uH_N
"""

from PIL import Image

import matplotlib.pyplot as plt



emoji_data = {

  "nome": "Smile",

  "grade": [

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],

    [(255,255,0), (0,0,0), (255,255,0), (0,0,0), (255,255,0)],

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],

    [(255,255,0), (0,0,0), (0,0,0), (0,0,0), (255,255,0)],

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)]

  ]

}





img = Image.new('RGB', (5, 5))





for i in range(5):

  for j in range(5):



    cor_original = emoji_data["grade"][i][j]





    if cor_original == (255, 255, 0):



      nova_cor = (cor_original[0] // 2, cor_original[1] // 2, 0)

    else:

      nova_cor = cor_original





    img.putpixel((j, i), nova_cor)





img_grande = img.resize((250, 250), resample=Image.NEAREST)



print(f"Emoji: {emoji_data['nome']} (Processado com Loops)")

plt.imshow(img_grande)

plt.axis('off')

plt.show()

biblioteca_musical = {

  "Toques": [

    {"Alegre": ([440, 480], [520, 560])},

    {"Triste": ([200, 150], [100, 50])}

  ]

}







for toque in biblioteca_musical["Toques"]:



  for nome_musica, matriz in toque.items():





    linha1, linha2 = matriz



    nova_matriz = (

      (linha1[0], linha2[0]),

      (linha1[1], linha2[1])

    )





    toque.update({nome_musica: nova_matriz})





print(biblioteca_musical)